# Generated by Django 2.2.3 on 2019-07-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checc',
            new_name='Order',
        ),
    ]
