# Generated by Django 2.2.3 on 2019-07-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checc', '0002_auto_20190718_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(default='--Empty--', max_length=100),
        ),
    ]
