# Generated by Django 2.2.3 on 2019-07-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checc', '0003_order_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(default='--Empty--', max_length=100),
        ),
    ]
